{
 "title": "Harvest of Quality",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tempo de Execução dos Builds (Percentis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_job_total_duration{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builds Instáveis",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builds Abortados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fila de Execução",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jenkins_queue_pending_value{job=\"jenkins\"}",
     "legendFormat": "__auto"
    },
    { "expr": "jenkins_queue_blocked_value", "legendFormat": "__auto" },
    { "expr": "jenkins_job_waiting_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU Jenkins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "system_cpu_load_x100_window_15m{job=\"jenkins\"}",
     "legendFormat": "__auto"
    },
    { "expr": "vm_cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Memória JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "vm_memory_heap_usage_x100_window_1h{job=\"jenkins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vm_memory_non_heap_usage_x100_window_15m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Execução Lighthouse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "jenkins_job_total_duration{job=\"lighthouse-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Falhas em Auditorias Lighthouse",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{job=\"lighthouse-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recursos durante Auditorias Lighthouse",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "system_cpu_load_x100_window_15m{job=\"lighthouse-job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vm_memory_heap_usage_x100_window_1h{job=\"lighthouse-job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}